### ISSUE TITLE
Unable to add security context on container level; no probes defined for access-logs container

### ISSUE THREAD

**Issue by michalschott** [haproxy-ingress/charts#35]
See https://github.com/haproxy-ingress/charts/pull/31

**Comment by jcmoraisjr** [comment]
Merged now, closing.

**Comment by jcmoraisjr** [comment]
0.13.5 now have this implementation, note however that I added a `controller.legacySecurityContext` which defaults to true, this needs to be changed to false in order to `controller.securityContext` to be applied to the controller container. This was done like that to preserve backward compatibility.
